# Generated by Django 5.0 on 2024-01-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_dept_count_alter_customuser_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dept',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
