# Generated by Django 5.0 on 2024-01-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('pause', 'Pause'), ('active', 'Active'), ('stater', 'Stater'), ('deleted', 'Deleted'), ('test', 'Test')], max_length=10),
        ),
    ]
