# Generated by Django 5.0.1 on 2024-01-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='study',
            field=models.CharField(blank=True, default='  ', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='visit_by',
            field=models.CharField(blank=True, default='  ', max_length=150, null=True),
        ),
    ]
