# Generated by Django 5.0.1 on 2024-01-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_study_customuser_visit_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='visit_by',
        ),
    ]
