# Generated by Django 5.0.1 on 2024-01-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_target_customuser_visit_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='study',
            field=models.CharField(blank=True, default=' Nomalum ', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='visit_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), to='users.target'),
        ),
    ]
