# Generated by Django 5.0.1 on 2024-01-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_study_alter_customuser_visit_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='visit_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(1), to='users.target'),
        ),
    ]
