# Generated by Django 5.0 on 2023-12-29 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.CharField(blank=True, max_length=25, null=True)),
                ('type', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_days', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=36)),
                ('added_lesson', models.BooleanField(default=False)),
                ('day1', models.CharField(choices=[('Dushanba', 'dushanba'), ('Seshanba', 'dushanba'), ('Chorshanba', 'chorshanba'), ('Pyshanba', 'payshanba'), ('Juma', 'juma'), ('Shanba', 'shanba')], max_length=12)),
                ('day2', models.CharField(choices=[('Dushanba', 'dushanba'), ('Seshanba', 'dushanba'), ('Chorshanba', 'chorshanba'), ('Pyshanba', 'payshanba'), ('Juma', 'juma'), ('Shanba', 'shanba')], max_length=12)),
                ('day3', models.CharField(choices=[('Dushanba', 'dushanba'), ('Seshanba', 'dushanba'), ('Chorshanba', 'chorshanba'), ('Pyshanba', 'payshanba'), ('Juma', 'juma'), ('Shanba', 'shanba')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='KindOfSpending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('count', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pay', models.FloatField()),
                ('type', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.course')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.days')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_day', models.DateField(auto_now_add=True)),
                ('started_day', models.DateField(blank=True, null=True)),
                ('pay_for', models.FloatField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(max_length=100)),
                ('for_smt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.kindofspending')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Yanvar', 'yanvar'), ('Fevral', 'fevral'), ('Mart', 'mart'), ('Aprel', 'aprel'), ('May', 'may'), ('Iyun', 'iyun'), ('Iyul', 'iyul'), ('Avgust', 'avgust'), ('Sentabr', 'sentabr'), ('Oktabr', 'oktabr'), ('Noyabr', 'noyabr'), ('Dekabr', 'dekabr')], max_length=20)),
                ('year', models.IntegerField(default=2023)),
                ('pay_date', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('dept', models.BooleanField(default=True)),
                ('dept_count', models.FloatField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField()),
                ('give', models.FloatField(blank=True, null=True)),
                ('not_give', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField(default=2023)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('given_date', models.DateField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('teacher', 'month', 'year')},
            },
        ),
    ]
