# Generated by Django 5.0 on 2023-12-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='days',
            name='day1',
            field=models.CharField(choices=[('Dushanba', 'dushanba'), ('Seshanba', 'seshanba'), ('Chorshanba', 'chorshanba'), ('Pyshanba', 'payshanba'), ('Juma', 'juma'), ('Shanba', 'shanba')], max_length=12),
        ),
        migrations.AlterField(
            model_name='days',
            name='day2',
            field=models.CharField(choices=[('Dushanba', 'dushanba'), ('Seshanba', 'seshanba'), ('Chorshanba', 'chorshanba'), ('Pyshanba', 'payshanba'), ('Juma', 'juma'), ('Shanba', 'shanba')], max_length=12),
        ),
        migrations.AlterField(
            model_name='days',
            name='day3',
            field=models.CharField(choices=[('Dushanba', 'dushanba'), ('Seshanba', 'seshanba'), ('Chorshanba', 'chorshanba'), ('Pyshanba', 'payshanba'), ('Juma', 'juma'), ('Shanba', 'shanba')], max_length=12),
        ),
    ]
