# Generated by Django 5.0 on 2023-12-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_payment_count_alter_days_day1_alter_days_day2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='month',
            field=models.CharField(choices=[('Yanvar', 'yanvar'), ('Fevral', 'fevral'), ('Mart', 'mart'), ('Aprel', 'aprel'), ('May', 'may'), ('Iyun', 'iyun'), ('Iyul', 'iyul'), ('Avgust', 'avgust'), ('Sentabr', 'sentabr'), ('Oktabr', 'oktabr'), ('Noyabr', 'noyabr'), ('Dekabr', 'dekabr')], max_length=20),
        ),
    ]
