# Generated by Django 5.0 on 2023-12-30 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_payment_card_payment_cash_alter_teachersalary_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='hour',
            field=models.IntegerField(default=8, max_length=2),
        ),
        migrations.AddField(
            model_name='group',
            name='minut',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
