# Generated by Django 5.0 on 2024-01-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_group_hour_group_minut_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='pay',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='dept_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='give',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='not_give',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
