# Generated by Django 5.0 on 2024-01-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_group_pay_alter_payment_dept_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='count',
            field=models.IntegerField(),
        ),
    ]
