# Generated by Django 5.0 on 2024-01-04 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_money_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='hour',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='group',
            name='minut',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('student', 'year', 'month', 'group')},
        ),
    ]
