# Generated by Django 5.0 on 2024-01-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_group_hour_alter_group_minut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='percentage',
            field=models.IntegerField(default=50),
        ),
    ]
