# Generated by Django 5.0 on 2024-01-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_group_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='card',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spending',
            name='cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spending',
            name='count',
            field=models.IntegerField(),
        ),
    ]
