# Generated by Django 5.0 on 2024-01-07 21:46

import django.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_spending_card_spending_cash_alter_spending_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('spending', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GivenSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('origin_count', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField()),
                ('card', models.IntegerField(blank=True, null=True)),
                ('cash', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.Empty, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
