# Generated by Django 5.0 on 2024-01-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_report_givensalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givensalary',
            name='month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='month',
            field=models.CharField(max_length=20),
        ),
    ]
