# Generated by Django 5.0 on 2024-01-07 22:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_givensalary_month_alter_report_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givensalary',
            name='date',
        ),
        migrations.AddField(
            model_name='report',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
