# Generated by Django 5.0.1 on 2024-01-09 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_givensalary_date_report_created_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=models.SET('Ochirilgan'), to=settings.AUTH_USER_MODEL),
        ),
    ]
