# Generated by Django 5.0.1 on 2024-01-11 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_payment_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.CharField(choices=[('Yanvar', 'yanvar'), ('Fevral', 'fevral'), ('Mart', 'mart'), ('Aprel', 'aprel'), ('May', 'may'), ('Iyun', 'iyun'), ('Iyul', 'iyul'), ('Avgust', 'avgust'), ('Sentabr', 'sentabr'), ('Oktabr', 'oktabr'), ('Noyabr', 'noyabr'), ('Dekabr', 'dekabr')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('percentage', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb', models.BooleanField(default=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
