# Generated by Django 5.0.1 on 2024-01-13 03:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_attendance_attendancestudent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('group', 'day', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancestudent',
            unique_together={('student', 'attendance')},
        ),
    ]
