# Generated by Django 5.0.1 on 2024-01-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_delete_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudent',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='groupstudent',
            name='is_sale',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='groupstudent',
            name='sale',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='groupstudent',
            name='teacher_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
