# Generated by Django 5.0.1 on 2024-01-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_groupstudent_count_groupstudent_is_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstudent',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='teacher_count',
            field=models.IntegerField(default=0),
        ),
    ]
